version: '3'
services:
  notes:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: notes
      POSTGRES_DB: notes
